version: "3.8"
services:
  spark_cluster_1:
    image: bitnami/spark:3.0.1
    container_name: spark_cluster_1
    networks:
      - dev-network
    ports:
      - "4040:4040"
    volumes:
      - ./my-src:/code/src
      - ./learning-spark:/code/learning-spark
      - ./.vscode-server:/root/.vscode-server
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    # command: "tail -f /dev/null"

networks:
  dev-network:
    name: learning-spark-network
    driver: bridge
